version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000/chat
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 